### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/teleg-api-bot#21]
New main topic: implement the plugin support.

All the functionality first discussed would be covered, so we could make it our "1.0".

**Comment by hecoding** [comment]
A good approach I think would be a component-based management of the plugins. And give an interface for the plugins to fill.

In the sense of:

``` python
bot.addPlugin(foo)

.......
class FooPlugin(Plugin):
    def retrieveBar(self):
        ...
    self.extend = {
        fooFunction() {
            ...
        }
    }
........

bot.fooFunction()
bot.foo.retrieveBar()
bot.delPlugin(foo)
```

I may have written an incoherence in the example since I don't use python very often, the structure of the `Plugin` class can be discussed later but you get the idea.

**Comment by DevPGSV** [comment]
I like it

**Comment by hecoding** [comment]
@Kuronogard a qué estamos esperando? esto va a tener un año

**Comment by dpriver** [comment]
I thought it may be a good idea to wait for more comments, but, since this is pretty quiet, better close it...
